### ISSUE TITLE
安装后使用报没有xcrawler.http模块

### ISSUE THREAD

**Issue by rainplus** [0xE8551CCB/xcrawler#6]
使用 python3.5 安装后测试baidu_news:

```
~/git/xcrawler/examples/baidu_news$ python3 run.py
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from xcrawler import Crawler
  File "/home/youboyone/.local/lib/python3.5/site-packages/xcrawler/__init__.py", line 1, in <module>
    from .crawler import Crawler
  File "/home/youboyone/.local/lib/python3.5/site-packages/xcrawler/crawler.py", line 14, in <module>
    from .engine import CrawlerEngine
  File "/home/youboyone/.local/lib/python3.5/site-packages/xcrawler/engine.py", line 16, in <module>
    from .http import Request, Response
ImportError: No module named 'xcrawler.http'
```

**Comment by 0xE8551CCB** [comment]
python3 -m run.py 试试？

**Comment by rainplus** [comment]
谢谢，应该使用scrapy代替了

**Comment by 0xE8551CCB** [comment]
OK，推荐 scrapy
